# Generated by Django 5.2.4 on 2025-09-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="stage",
            field=models.CharField(
                choices=[
                    ("qualification", "Qualification"),
                    ("meet_present", "Meet/Present"),
                    ("proposal", "Proposal"),
                    ("negotiation", "Negotiation"),
                    ("closed_won", "Closed Won"),
                    ("closed_lost", "Closed Lost"),
                ],
                default="qualification",
                max_length=20,
            ),
        ),
    ]
