# Generated by Django 5.2.4 on 2025-09-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0003_opportunitylineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunitylineitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="opportunitylineitem",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
