# Generated by Django 5.2.4 on 2025-08-22 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("customer", "Customer"),
                            ("partner", "Partner"),
                            ("competitor", "Competitor"),
                        ],
                        default="prospect",
                        max_length=20,
                    ),
                ),
                ("billing_address", models.TextField(blank=True)),
                ("shipping_address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_accounts",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="accounts_ac_name_5f6f46_idx"),
                    models.Index(fields=["type"], name="accounts_ac_type_cd282c_idx"),
                    models.Index(
                        fields=["is_active"], name="accounts_ac_is_acti_b52bc0_idx"
                    ),
                ],
            },
        ),
    ]
