# Generated by Django 5.2.4 on 2025-08-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
