# Generated by Django 5.2.4 on 2025-08-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
