# crm-project/docker-compose.yml

services:
  api:
    build: ./backend
    # This command MUST specify the port INSIDE the container. Keep it as 8000.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    # This section maps HOST port to CONTAINER port. This is what you change.
    ports:
      - "8001:8000" # Host port 8001 is mapped to container port 8000
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env

volumes:
  postgres_data:
