# Generated by Django 5.2.4 on 2025-09-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Fulfillment", "Pending Fulfillment"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending Fulfillment",
                max_length=25,
            ),
        ),
    ]
