# Generated by Django 5.2.4 on 2025-09-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Active", "Active"),
                    ("Expired", "Expired"),
                    ("Terminated", "Terminated"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
