# Generated by Django 5.2.4 on 2025-10-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
        ("contacts", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Multiple contacts related to this activity (Name field).",
                related_name="related_activities",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="leads",
            field=models.ManyToManyField(
                blank=True,
                help_text="Multiple leads related to this activity (Name field).",
                related_name="related_activities",
                to="leads.lead",
            ),
        ),
    ]
