# Generated by Django 5.2.4 on 2025-10-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_activity_contacts_activity_leads"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="activity",
            name="only_one_who_fk",
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="activities__contact_9b9b6b_idx",
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="activities__lead_id_48f544_idx",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="lead",
        ),
    ]
