# Generated by Django 5.2.4 on 2025-09-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_name"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="invoice",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="accounts.account",
            ),
        ),
    ]
