# Generated by Django 5.2.4 on 2025-09-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_remove_invoice_total_amount_invoice_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Awaiting Payment", "Awaiting Payment"),
                    ("Partially Paid", "Partially Paid"),
                    ("Paid in Full", "Paid in Full"),
                    ("Fulfilled", "Fulfilled"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Awaiting Payment",
                max_length=20,
            ),
        ),
    ]
