# Generated by Django 5.2.4 on 2025-09-09 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("billing_address", models.TextField(blank=True)),
                ("shipping_address", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Contacted", "Contacted"),
                            ("Qualified", "Qualified"),
                            ("Converted", "Converted"),
                        ],
                        default="New",
                        max_length=20,
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Website", "Website"),
                            ("Referral", "Referral"),
                            ("Partner", "Partner"),
                            ("Cold Call", "Cold Call"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company"], name="leads_lead_company_8dadd2_idx"
                    ),
                    models.Index(
                        fields=["last_name"], name="leads_lead_last_na_961118_idx"
                    ),
                ],
            },
        ),
    ]
